// pages/index.tsx
import { NextPage } from "next";
import Head from "next/head";

const Test: NextPage = () => {
  return (
    <div>
      <Head>
        <title>My Next.js TypeScript App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center min-h-screen">
        <h1 className="text-4xl font-bold text-balance">
          Welcome to My Next.js TypeScript App!
        </h1>
        <p className="mt-4 text-lg">
          This is a simple example to test Tailwind CSS and custom styles.
        </p>
      </main>
    </div>
  );
};

export default Test;
